[build-system]
requires = ["maturin>=1.13,<2.0"]
build-backend = "maturin"

[project]
name = "textstat-rs"
description = "Rust port of the textstat textual analysis library, with Python bindings."
readme = "README.md"
license = "MIT"
# The MIT license covers code in this package
# Third party data in src/data has it's license preserved
# More information in README.md
license-files = [
    "LICENSE",
    "src/data/cmudict-LICENSE.txt",
    "src/data/pyphen-LICENSE.txt",
    "src/data/README_hyph_en_US.txt",
    "src/data/README_hyph_en_GB.txt",
]
requires-python = ">=3.10"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Topic :: Text Processing :: Linguistic",
    "Programming Language :: Rust",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: Implementation :: CPython",
]
dynamic = ["version"]
dependencies = []

[project.urls]
Homepage = "https://github.com/CZboop/textstat-rs"
Repository = "https://github.com/CZboop/textstat-rs"
Issues = "https://github.com/CZboop/textstat-rs/issues"

[project.optional-dependencies]
dev = [
    "datasets==3.6.0",
    "pytest>=8.3.5",
    "textstat>=0.7.13",
    "nltk",
    "maturin",
    "mypy",
]

[tool.maturin]
python-source = "python"
