"""Type stubs for the compiled `textstat_rs` extension module.

Signatures mirror the `#[pyo3(signature = ...)]` declarations in `src/lib.rs`;
keep the two in step when adding or changing a metric.
"""

__all__ = [
    "automated_readability_index",
    "char_count",
    "coleman_liau_index",
    "dale_chall_readability_score",
    "difficult_words",
    "flesch_kincaid_grade",
    "flesch_reading_ease",
    "gunning_fog",
    "letter_count",
    "lexicon_count",
    "linsear_write_formula",
    "mcalpine_eflaw",
    "miniword_count",
    "polysyllabcount",
    "reading_time",
    "sentence_count",
    "smog_index",
    "spache_readability",
    "syllable_count",
    "text_standard",
]

# Metrics

def flesch_reading_ease(text: str) -> float: ...
def flesch_kincaid_grade(text: str) -> float: ...
def automated_readability_index(text: str) -> float: ...
def coleman_liau_index(text: str) -> float: ...
def dale_chall_readability_score(text: str) -> float: ...
def smog_index(text: str) -> float: ...
def spache_readability(text: str) -> float: ...
def mcalpine_eflaw(text: str) -> float: ...
def linsear_write_formula(
    text: str, strict_lower: bool = False, strict_upper: bool = True
) -> float: ...
def gunning_fog(text: str, syllable_threshold: int = 3) -> float: ...
def reading_time(text: str, ms_per_char: float = 14.69) -> float: ...
def text_standard(text: str) -> str: ...

# Counts

def syllable_count(text: str) -> int: ...
def sentence_count(text: str) -> int: ...
def letter_count(text: str) -> int: ...
def polysyllabcount(text: str) -> int: ...
def char_count(text: str, ignore_spaces: bool = True) -> int: ...
def miniword_count(text: str, max_size: int = 3) -> int: ...
def difficult_words(
    text: str, syllable_threshold: int = 2, unique: bool = True
) -> int: ...
def lexicon_count(
    text: str,
    removepunct: bool = True,
    split_contractions: bool = False,
    split_hyphens: bool = False,
) -> int: ...
